# UC San Diego: Data Science in Practice - Data Checkpoint
### Summer Session I 2023 | Instructor : C. Alex Simpkins Ph.D.

## Draft project title if you have one (can be changed later)

# Names

- Arjun Varshney
- Hao Luong
- Yaotian Wu
- Joy Yue Lam
- Mengming Luo 
- Sina Radi

<a id='research_question'></a>
# Research Question

* How did regional factors such as differences in income levels, education, and COVID relief impact mobility patterns in the Bay Area and the Central Valley during COVID-19?

# Dataset(s)

**On Mobility —**

* Dataset Name: COVID-19: Google Mobility Trends
* Link: https://ourworldindata.org/covid-google-mobility-trends
* Number of observations: 67,456
* Dataset description: The Google Mobility dataset tracks the mobility of people world wide during the COVID-19 pandemic. For our purposes, we used Google’s Mobility data on California and analyzed the mobility trends of Merced for Central Valley and Alameda for the Bay Area. Google categorized their mobility data based on “retail & recreation”, “grocery & pharmacy”, “parks”, “transit stations”, “workplaces”, and “residential”. These data during the pandemic will be useful for us to analyze how influential the COVID-19 pandemic was on mobility in the Bay Area and Central Valley.

**On Mortality —**

* Dataset Name: COVID-19 Time-Series Metrics by County and State
* Link: https://catalog.data.gov/dataset/covid-19-time-series-metrics-by-county-and-state-c75b0
* Number of observations: 1258
* Dataset description: This dataset documents the number of deaths by COVID per day in counties across California, officially published by the California Department of Health. From this dataset we plan on comparing the number of COVID fatalities between Central Valley (Alameda) and the Bay Area (Merced) in order to evaluate the impact of the COVID-19 virus on the two regions.

**On Income —**

* Dataset Name: Unemployment and median household income for the U.S., States, and counties, 2000–22
* Link: https://www.ers.usda.gov/webdocs/DataFiles/48747/Unemployment.xlsx?v=2447.8
* Number of observations: 3,282
* Dataset description: The dataset is from the USDA economic research service (ERS) taking into account the socioeconomic indicators. The data seems to focus more on bigger cities, since there is another sub-dataset for rural areas and small downs. ERS databases looks at both urban and rural areas separately, so this dataset can help us assess the differences of income between the Central Valley and the Bay Area during the COVID-19 pandemic..

**On Education —**

* Dataset Name: Educational attainment for adults age 25 and older for the U.S., States, and counties, 1970–2021
* Link: https://www.ers.usda.gov/webdocs/DataFiles/48747/Education.xlsx?v=2447.8
* Number of observations: 3,289
* Dataset description: The dataset, also from the ERS of the USDA, looks at the completion rates of schools until 2021, considering varying levels of educational attainment. The data is broken down into these different levels, which are a bit generalized into the duration it takes to get that degree, and does not look at the individual years required.

**COVID Relief —**

* Dataset Name: Unemployment Benefits Data
* Link: https://edd.ca.gov/siteassets/files/newsroom/facts-and-stats/excel/state-county-dashboard-071223.xlsx
* Number of observations: 21,224
* Dataset description: This Employment Development Department (EDD) dataset delivers the data regarding the unemployment benefits which the EDD was bombarded to quickly process and disburse, during COVID. The data is essential, since it explores existing unemployment insurance (UI) claims and new ones. The data is made up of the voluntary responses of UI claimants as they were filling out the application to receive unemployment, which was most likely done on the computer, on their website. It is important to note the dataset also includes Pandemic Unemployment Assistance (PUA), which disbursed more money due to federal government support during the pandemic, and expired September of 2021.

**On Transmission —**

* Dataset Name: United States COVID-19 County Level of Community Transmission Historical Changes
* Link: https://catalog.data.gov/dataset/united-states-covid-19-county-level-of-community-transmission-historical-changes
* Number of observations: 1,048,576
* Dataset description: U.S. Department of Health & Human Services dataset records the rate of COVID-19 transmission by tracking the change in cases per 100,000 people every week and evaluating the community transmission level (of 'low', 'moderate', 'substantial', and 'high' transmission) in each state and county. Some values are “suppressed” to maintain privacy standards or due to data quality issues. This data is important because by tracking the rate of transmission of COVID-19 cases, we are able to assess how severely impact areas are by the pandemic over time and how that affects mobility.

**On Vaccination —**

* Dataset Name: Statewide COVID-19 Vaccines Administered By County
* Link: https://data.ca.gov/dataset/covid-19-vaccine-progress-dashboard-data/resource/eef88868-0cfc-4655-8a5a-3d1af1d23498
* Number of observations: 67,456
* Dataset description: The data examines vaccination rates and applies to out research, since we need data broken down by counties, only within California. Although the dataset includes in great detail of certain manufacturers, those columns are to be ignored, given they do not add much value to our purpose. The data includes both types of boosters, as well as regular vaccines.

# Data Wrangling

In [1]:
# importing all of the libraries 
import pandas as pd
import numpy as np
import datetime

In [2]:
#education dataset
#reading the file
data = pd.read_csv('education raw.csv', header =3) #(header=3 fixes the headers)
#remove first row
data = data.iloc[1:]
#Showing only Alameda County and Merced
A_M = data[(data['Area name'] == 'Alameda County') | (data['Area name'] == 'Merced County')]
#Selecting specific columns
AMY = A_M.drop(A_M.iloc[:, 3:47], axis=1)
#export as 'education.csv'
AMY.to_csv('education.csv')

In [3]:
#income dataset
#read the file
data = pd.read_csv('income raw.csv', header = 4)
#selecting only Alameda and Merced County
data = data[(data['Area_Name'] == 'Alameda County, CA') | (data['Area_Name'] == 'Merced County, CA')]
#Selecting only columns State, Area_Name, and Median Household Income of 2021
data = data.loc[:,['State','Area_Name','Median_Household_Income_2021']]
data
#export as 'income.csv'
data.to_csv('income.csv')

In [4]:
#transmission dataset
#read the file
data = pd.read_csv('transmission raw.csv')
#selecting Alameda and Merced County
data_ALA = data[(data['county_name'] == 'Alameda County')]
data_MER = data[(data['county_name'] == 'Merced County')]
#convert 'date' column to datetime datatype
data_ALA['date'] = pd.to_datetime(data_ALA['date'])
data_MER['date'] = pd.to_datetime(data_MER['date'])
#sort data by date
data_ALA = data_ALA.sort_values(by=['date'], ascending = True)
data_MER = data_MER.sort_values(by=['date'], ascending = True)
#stack data_ALA and data_MER together
transmission = pd.concat([data_ALA, data_MER], axis=0)
#export as 'transmission.csv'
transmission.to_csv('transmission.csv')

/tmp/ipykernel_3776/2467239479.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_ALA['date'] = pd.to_datetime(data_ALA['date'])
/tmp/ipykernel_3776/2467239479.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_MER['date'] = pd.to_datetime(data_MER['date'])

In [5]:
#covidrelief
#read the file
data = pd.read_csv('covidrelief raw.csv', header = 3)
#selecting Alameda and Merced County
data_ALA = data[(data['County'] == 'Alameda')]
data_MER = data[(data['County'] == 'Merced')]
#convert 'Week Ending' column to datetime datatype
data_ALA['Week Ending'] = pd.to_datetime(data_ALA['Week Ending'])
data_MER['Week Ending'] = pd.to_datetime(data_MER['Week Ending'])
#sort data by date
data_ALA = data_ALA.sort_values(by=['Week Ending'], ascending = True)
data_MER = data_MER.sort_values(by=['Week Ending'], ascending = True)
#stack data_ALA and data_MER together
covidrelief = pd.concat([data_ALA, data_MER], axis=0)
#export as 'covidrelief.csv'
covidrelief.to_csv('covidrelief.csv')

/tmp/ipykernel_3776/4109015138.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_ALA['Week Ending'] = pd.to_datetime(data_ALA['Week Ending'])
/tmp/ipykernel_3776/4109015138.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_MER['Week Ending'] = pd.to_datetime(data_MER['Week Ending'])

In [6]:
#vaccination
#read the file
data = pd.read_csv('vaccination raw.csv')
#selecting Alameda and Merced County
data_ALA = data[(data['county'] == 'Alameda')]
data_MER = data[(data['county'] == 'Merced')]
#convert 'administered_date' column to datetime datatype
data_ALA['administered_date'] = pd.to_datetime(data_ALA['administered_date'])
data_MER['administered_date'] = pd.to_datetime(data_MER['administered_date'])
#sort data by date
data_ALA = data_ALA.sort_values(by=['administered_date'], ascending = True)
data_MER = data_MER.sort_values(by=['administered_date'], ascending = True)
#stack data_ALA and data_MER together
vaccination = pd.concat([data_ALA, data_MER], axis=0)

vaccination = vaccination.iloc[:,0:]
#export as 'vaccination.csv'
vaccination.to_csv('vaccination.csv')

/tmp/ipykernel_3776/2846971121.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_ALA['administered_date'] = pd.to_datetime(data_ALA['administered_date'])
/tmp/ipykernel_3776/2846971121.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_MER['administered_date'] = pd.to_datetime(data_MER['administered_date'])

In [7]:
#mortality
#read the file
data = pd.read_csv('mortality raw.csv')
#selecting Alameda and Merced County
data_ALA = data[(data['area'] == 'Alameda')]
data_MER = data[(data['area'] == 'Merced')]
#convert 'administered_date' column to datetime datatype
data_ALA['date'] = pd.to_datetime(data_ALA['date'])
data_MER['date'] = pd.to_datetime(data_MER['date'])
#sort data by date
data_ALA = data_ALA.sort_values(by=['date'], ascending = True)
data_MER = data_MER.sort_values(by=['date'], ascending = True)
#stack data_ALA and data_MER together
mortality = pd.concat([data_ALA, data_MER], axis=0)
#export as 'mortality.csv'
mortality.to_csv('mortality.csv')

/tmp/ipykernel_3776/156495032.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_ALA['date'] = pd.to_datetime(data_ALA['date'])
/tmp/ipykernel_3776/156495032.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_MER['date'] = pd.to_datetime(data_MER['date'])

In [8]:
#mobility
#read the file
data1 = pd.read_csv('2020 mobility.csv')
data2 = pd.read_csv('2021 mobility.csv')
data3 = pd.read_csv('2022 mobility.csv')
#combine 2020 2021 2022 data
data = pd.concat([data1, data2, data3], axis=0)
#select California
data = data[(data['sub_region_1'] == 'California')]
#selecting Alameda and Merced County
data_ALA = data[(data['sub_region_2'] == 'Alameda County')]
data_MER = data[(data['sub_region_2'] == 'Merced County')]
#convert 'administered_date' column to datetime datatype
data_ALA['date'] = pd.to_datetime(data_ALA['date'])
data_MER['date'] = pd.to_datetime(data_MER['date'])
#sort data by date
data_ALA = data_ALA.sort_values(by=['date'], ascending = True)
data_MER = data_MER.sort_values(by=['date'], ascending = True)
#stack data_ALA and data_MER together
mobility = pd.concat([data_ALA, data_MER], axis=0)
#export as 'mobility.csv'
mobility.to_csv('mobility.csv')

/tmp/ipykernel_3776/3612169399.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_ALA['date'] = pd.to_datetime(data_ALA['date'])
/tmp/ipykernel_3776/3612169399.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_MER['date'] = pd.to_datetime(data_MER['date'])

In [9]:
#load all of the csv files 
covidrelief = pd.read_csv('covidrelief.csv')
mobility = pd.read_csv('mobility.csv')
mortality = pd.read_csv('mortality.csv')
transmission = pd.read_csv('transmission.csv')
vaccination = pd.read_csv('vaccination.csv')
education = pd.read_csv('education.csv')

In [10]:
#covidrelief dataset
covidrelief.dtypes

Unnamed: 0            int64
Week Ending          object
County               object
Initial UI Claims    object
Claim Type           object
dtype: object

In [11]:
#renaming 'Week Ending' column to 'date'
covidrelief.rename(columns = {'Week Ending':'date'}, inplace = True)

#convert 'date' column values to datetime value
covidrelief['date']= pd.to_datetime(covidrelief['date'])

#covidrelief#.groupby(['date','County']).sum()
dates = covidrelief['date'].values
#for i in dates:
    #curr_df = covidrelief[covidrelief[‘date’]==i]
    #curr_df[‘Claim Type’].values
    #curr_df[‘New Col’] = curr_df[‘Claim Type’].values[0] + ‘,’ + curr_df[‘Claim Type’].values[1]
#need to combine UI claims and PUA claims as there are 2 observations with same dates

In [12]:
#mobility dataset
mobility.dtypes

#replacing '########' values to 'NaN'
mobility=mobility.replace('#########', 'NaN')

#renaming 'sub_region_2' column to 'County'
mobility.rename(columns = {'sub_region_2':'County'}, inplace = True)

#convert 'date' column values to datetime value
mobility['date']= pd.to_datetime(mobility['date'])

#dropping null values
mobility.dropna(subset = ['date'], inplace=True)

#replace "Alameda County" & "Merced County" with just Alameda & Merced
mobility['County'] = mobility['County'].replace(['Alameda County'], 'Alameda')
mobility['County'] = mobility['County'].replace(['Merced County'], 'Merced')


#print mobility data
mobility

,Unnamed: 0,country_region_code,country_region,sub_region_1,County,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,48386,US,United States,California,Alameda,NaN,NaN,6001.0,ChIJWRd5NDfyj4ARc30TGxHHxmg,2020-02-15,1.0,0.0,22.0,1.0,0.0,-1.0
1,48387,US,United States,California,Alameda,NaN,NaN,6001.0,ChIJWRd5NDfyj4ARc30TGxHHxmg,2020-02-16,7.0,0.0,24.0,5.0,1.0,-2.0
2,48388,US,United States,California,Alameda,NaN,NaN,6001.0,ChIJWRd5NDfyj4ARc30TGxHHxmg,2020-02-17,13.0,1.0,55.0,-31.0,-53.0,11.0
3,48389,US,United States,California,Alameda,NaN,NaN,6001.0,ChIJWRd5NDfyj4ARc30TGxHHxmg,2020-02-18,-2.0,3.0,21.0,3.0,0.0,0.0
4,48390,US,United States,California,Alameda,NaN,NaN,6001.0,ChIJWRd5NDfyj4ARc30TGxHHxmg,2020-02-19,-1.0,0.0,14.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1943,51342,US,United States,California,Merced,NaN,NaN,6047.0,ChIJV3GZ91BAkYARa-nZLEDidHY,2022-10-11,-9.0,-13.0,37.0,-27.0,-7.0,1.0
1944,51343,US,United States,California,Merced,NaN,NaN,6047.0,ChIJV3GZ91BAkYARa-nZLEDidHY,2022-10-12,-7.0,-9.0,30.0,-22.0,-8.0,1.0
1945,51344,US,United States,California,Merced,NaN,NaN,6047.0,ChIJV3GZ91BAkYARa-nZLEDidHY,2022-10-13,-7.0,-11.0,31.0,-21.0,-5.0,0.0
1946,51345,US,United States,California,Merced,NaN,NaN,6047.0,ChIJV3GZ91BAkYARa-nZLEDidHY,2022-10-14,-6.0,-8.0,41.0,-21.0,-8.0,1.0
1947,51346,US,United States,California,Merced,NaN,NaN,6047.0,ChIJV3GZ91BAkYARa-nZLEDidHY,2022-10-15,-6.0,-11.0,67.0,-25.0,-1.0,-1.0

In [13]:
#mortality dataset
mortality.dtypes

#convert 'date' column values to datetime value
mortality['date']= pd.to_datetime(mortality['date'])

#renaming 'county_name' column to 'County'
mortality.rename(columns = {'area':'County'}, inplace = True)

#print mortality data
mortality

,Unnamed: 0,date,County,area_type,population,cases,cumulative_cases,deaths,cumulative_deaths,total_tests,cumulative_total_tests,positive_tests,cumulative_positive_tests
0,0,2020-02-01,Alameda,County,1685886.0,3.0,3.0,0.0,0.0,4.0,4,0.0,0
1,1,2020-02-02,Alameda,County,1685886.0,0.0,3.0,0.0,0.0,1.0,5,0.0,0
2,2,2020-02-03,Alameda,County,1685886.0,0.0,3.0,0.0,0.0,0.0,5,0.0,0
3,3,2020-02-04,Alameda,County,1685886.0,0.0,3.0,0.0,0.0,0.0,5,0.0,0
4,4,2020-02-05,Alameda,County,1685886.0,0.0,3.0,0.0,0.0,1.0,6,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2525,31620,2023-07-15,Merced,County,287420.0,1.0,78693.0,0.0,904.0,28.0,883004,2.0,91707
2526,31621,2023-07-16,Merced,County,287420.0,1.0,78694.0,0.0,904.0,25.0,883029,1.0,91708
2527,31622,2023-07-17,Merced,County,287420.0,3.0,78697.0,0.0,904.0,27.0,883056,4.0,91712
2528,31623,2023-07-18,Merced,County,287420.0,0.0,78697.0,0.0,904.0,NaN,883056,NaN,91712
2529,31624,NaT,Merced,County,287420.0,4.0,78701.0,0.0,904.0,326.0,883382,66.0,91778

In [14]:
#transmission dataset
transmission

#convert 'date' column values to datetime value
transmission['date']= pd.to_datetime(transmission['date'])

#renaming 'county_name' column to 'County'
transmission.rename(columns = {'county_name':'County'}, inplace = True)

#standardize name function
def standardize_name(str_in):
    
    try:
        str_in = str_in.lower()
        str_in = str_in.strip()

        if 'county' in str_in:
            str_in = str_in.replace('county', '')
            output = str_in
        
        else:
            output = np.nan
    except:
        output = np.nan
        
    return output

#applying standardize_name function to 'County' column of transmission data
transmission['County'] = transmission['County'].apply(standardize_name)

#Capitalizing values in 'County' column of transmission data
transmission['County'] = transmission['County'].str.capitalize()

#print transmission dataset
transmission

,Unnamed: 0,state_name,County,fips_code,date,cases_per_100K_7_day_count_change,percent_test_results_reported_positive_last_7_days,community_transmission_level
0,1795,California,Alameda,6001,2020-01-26,0.000,NaN,NaN
1,395794,California,Alameda,6001,2020-01-27,0.000,NaN,NaN
2,6730,California,Alameda,6001,2020-01-31,0.000,NaN,low
3,399009,California,Alameda,6001,2020-02-05,0.000,NaN,low
4,402543,California,Alameda,6001,2020-02-06,0.000,NaN,low
...,...,...,...,...,...,...,...,...
513,781287,California,Merced,6047,2022-09-21,85.710,6.69,substantial
514,391137,California,Merced,6047,2022-09-22,85.710,6.51,substantial
515,786030,California,Merced,6047,2022-10-04,119.562,4.45,high
516,391891,California,Merced,6047,2022-10-09,55.099,4.66,substantial
517,485,California,Merced,6047,2022-10-17,39.614,NaN,moderate

In [15]:
#vaccination dataset
vaccination

#convert 'administered_date' column values to datetime value
vaccination['administered_date']= pd.to_datetime(vaccination['administered_date'])

#renaming 'county' column to 'County'
vaccination.rename(columns = {'county':'County'}, inplace = True)

#renaming 'administered_date' column to 'date'
vaccination.rename(columns = {'administered_date':'date'}, inplace = True)

#print vaccination data
vaccination

,Unnamed: 0,County,date,total_doses,cumulative_total_doses,pfizer_doses,cumulative_pfizer_doses,moderna_doses,cumulative_moderna_doses,jj_doses,...,cumulative_at_least_one_dose,california_flag,booster_recip_count,bivalent_booster_recip_count,cumulative_booster_recip_count,cumulative_bivalent_booster_recip_count,up_to_date_count,cumulative_up_to_date_count,booster_eligible_population,bivalent_booster_eligible_population
0,0,Alameda,2020-01-05,0,0,0,0,0,0,0,...,0,NaN,0,0,0,0,0,0,1405462,1405462
1,1,Alameda,2020-07-27,0,0,0,0,0,0,0,...,0,NaN,0,0,0,0,0,0,1405462,1405462
2,13568,Alameda,2020-07-28,1,1,0,0,1,1,0,...,1,California,0,0,0,0,0,0,1405462,1405462
3,2,Alameda,2020-07-29,0,1,0,0,0,1,0,...,1,NaN,0,0,0,0,0,0,1405462,1405462
4,3,Alameda,2020-07-30,0,1,0,0,0,1,0,...,1,NaN,0,0,0,0,0,0,1405462,1405462
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2181,35533,Merced,2023-07-19,16,439617,7,275816,9,148841,0,...,180227,California,8,8,76269,21454,14,23341,158662,158662
2182,35534,Merced,2023-07-20,14,439631,9,275825,5,148846,0,...,180234,California,3,3,76272,21457,14,23355,158662,158662
2183,35535,Merced,2023-07-21,9,439640,5,275830,4,148850,0,...,180234,California,8,8,76280,21465,8,23363,158662,158662
2184,35536,Merced,2023-07-22,3,439643,2,275832,1,148851,0,...,180234,California,2,2,76282,21467,3,23366,158662,158662
2185,6448,Merced,2023-07-23,0,439643,0,275832,0,148851,0,...,180234,NaN,0,0,76282,21467,0,23366,158662,158662

In [16]:
#merge mobility and mortality datasets
merged_df = pd.merge(mobility, mortality, on=['date', 'County'], how='outer')

#merge merged_df and transmission datasets
merged_df1 = pd.merge(merged_df, transmission, on=['date', 'County'], how='outer')
#new_df= merged_df.dropna(how='any')

#merge merged_df1 and vaccination datasets
merged_df2 = pd.merge(merged_df1, vaccination, on=['date', 'County'], how='outer')
merged_df2

/tmp/ipykernel_3776/3561242494.py:9: FutureWarning: Passing 'suffixes' which cause duplicate columns {'Unnamed: 0_x'} in the result is deprecated and will raise a MergeError in a future version.
  merged_df2 = pd.merge(merged_df1, vaccination, on=['date', 'County'], how='outer')

,Unnamed: 0_x,country_region_code,country_region,sub_region_1,County,metro_area,iso_3166_2_code,census_fips_code,place_id,date,...,cumulative_at_least_one_dose,california_flag,booster_recip_count,bivalent_booster_recip_count,cumulative_booster_recip_count,cumulative_bivalent_booster_recip_count,up_to_date_count,cumulative_up_to_date_count,booster_eligible_population,bivalent_booster_eligible_population
0,48386.0,US,United States,California,Alameda,NaN,NaN,6001.0,ChIJWRd5NDfyj4ARc30TGxHHxmg,2020-02-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,48387.0,US,United States,California,Alameda,NaN,NaN,6001.0,ChIJWRd5NDfyj4ARc30TGxHHxmg,2020-02-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,48388.0,US,United States,California,Alameda,NaN,NaN,6001.0,ChIJWRd5NDfyj4ARc30TGxHHxmg,2020-02-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,48389.0,US,United States,California,Alameda,NaN,NaN,6001.0,ChIJWRd5NDfyj4ARc30TGxHHxmg,2020-02-18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,48390.0,US,United States,California,Alameda,NaN,NaN,6001.0,ChIJWRd5NDfyj4ARc30TGxHHxmg,2020-02-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3055,NaN,NaN,NaN,NaN,Merced,NaN,NaN,NaN,NaN,2023-07-19,...,180227.0,California,8.0,8.0,76269.0,21454.0,14.0,23341.0,158662.0,158662.0
3056,NaN,NaN,NaN,NaN,Merced,NaN,NaN,NaN,NaN,2023-07-20,...,180234.0,California,3.0,3.0,76272.0,21457.0,14.0,23355.0,158662.0,158662.0
3057,NaN,NaN,NaN,NaN,Merced,NaN,NaN,NaN,NaN,2023-07-21,...,180234.0,California,8.0,8.0,76280.0,21465.0,8.0,23363.0,158662.0,158662.0
3058,NaN,NaN,NaN,NaN,Merced,NaN,NaN,NaN,NaN,2023-07-22,...,180234.0,California,2.0,2.0,76282.0,21467.0,3.0,23366.0,158662.0,158662.0
3059,NaN,NaN,NaN,NaN,Merced,NaN,NaN,NaN,NaN,2023-07-23,...,180234.0,NaN,0.0,0.0,76282.0,21467.0,0.0,23366.0,158662.0,158662.0

# Data Cleaning

Describe your data cleaning steps here.

In [17]:
merged_df2.columns

Index(['Unnamed: 0_x', 'country_region_code', 'country_region', 'sub_region_1',
       'County', 'metro_area', 'iso_3166_2_code', 'census_fips_code',
       'place_id', 'date',
       'retail_and_recreation_percent_change_from_baseline',
       'grocery_and_pharmacy_percent_change_from_baseline',
       'parks_percent_change_from_baseline',
       'transit_stations_percent_change_from_baseline',
       'workplaces_percent_change_from_baseline',
       'residential_percent_change_from_baseline', 'Unnamed: 0_y', 'area_type',
       'population', 'cases', 'cumulative_cases', 'deaths',
       'cumulative_deaths', 'total_tests', 'cumulative_total_tests',
       'positive_tests', 'cumulative_positive_tests', 'Unnamed: 0_x',
       'state_name', 'fips_code', 'cases_per_100K_7_day_count_change',
       'percent_test_results_reported_positive_last_7_days',
       'community_transmission_level', 'Unnamed: 0_y', 'total_doses',
       'cumulative_total_doses', 'pfizer_doses', 'cumulative_pfizer_doses',
       'moderna_doses', 'cumulative_moderna_doses', 'jj_doses',
       'cumulative_jj_doses', 'partially_vaccinated',
       'total_partially_vaccinated', 'fully_vaccinated',
       'cumulative_fully_vaccinated', 'at_least_one_dose',
       'cumulative_at_least_one_dose', 'california_flag',
       'booster_recip_count', 'bivalent_booster_recip_count',
       'cumulative_booster_recip_count',
       'cumulative_bivalent_booster_recip_count', 'up_to_date_count',
       'cumulative_up_to_date_count', 'booster_eligible_population',
       'bivalent_booster_eligible_population'],
      dtype='object')

In [18]:
new_df = merged_df2[['County', 'date','retail_and_recreation_percent_change_from_baseline',
       'grocery_and_pharmacy_percent_change_from_baseline',
       'parks_percent_change_from_baseline',
       'transit_stations_percent_change_from_baseline',
       'workplaces_percent_change_from_baseline',
       'residential_percent_change_from_baseline', 'cumulative_cases', 'deaths', 'cumulative_deaths', 'cumulative_total_tests','positive_tests', 'cumulative_positive_tests',
       'cumulative_total_doses','total_partially_vaccinated','cumulative_fully_vaccinated', 'cumulative_at_least_one_dose','cumulative_booster_recip_count',
       'cumulative_bivalent_booster_recip_count','booster_eligible_population',
       'bivalent_booster_eligible_population' ]]

#transmission columns are removed

In [19]:
new_df

,County,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline,cumulative_cases,deaths,...,positive_tests,cumulative_positive_tests,cumulative_total_doses,total_partially_vaccinated,cumulative_fully_vaccinated,cumulative_at_least_one_dose,cumulative_booster_recip_count,cumulative_bivalent_booster_recip_count,booster_eligible_population,bivalent_booster_eligible_population
0,Alameda,2020-02-15,1.0,0.0,22.0,1.0,0.0,-1.0,6.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alameda,2020-02-16,7.0,0.0,24.0,5.0,1.0,-2.0,6.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Alameda,2020-02-17,13.0,1.0,55.0,-31.0,-53.0,11.0,7.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Alameda,2020-02-18,-2.0,3.0,21.0,3.0,0.0,0.0,7.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Alameda,2020-02-19,-1.0,0.0,14.0,1.0,0.0,0.0,7.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3055,Merced,2023-07-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,439617.0,21496.0,158720.0,180227.0,76269.0,21454.0,158662.0,158662.0
3056,Merced,2023-07-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,439631.0,21503.0,158720.0,180234.0,76272.0,21457.0,158662.0,158662.0
3057,Merced,2023-07-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,439640.0,21503.0,158720.0,180234.0,76280.0,21465.0,158662.0,158662.0
3058,Merced,2023-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,439643.0,21503.0,158720.0,180234.0,76282.0,21467.0,158662.0,158662.0
3059,Merced,2023-07-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,439643.0,21503.0,158720.0,180234.0,76282.0,21467.0,158662.0,158662.0

In [20]:
start_date = '2020-08-21'
end_date = '2022-09-10'

# Select DataFrame rows between two dates
#new_df1 = (new_df['date'] > start_date) & (new_df['date'] <= end_date)
#new_df2 = new_df1.loc[new_df1]
#new_df1
df = new_df.query('date >= @start_date and date <= @end_date')

In [21]:
df

,County,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline,cumulative_cases,deaths,...,positive_tests,cumulative_positive_tests,cumulative_total_doses,total_partially_vaccinated,cumulative_fully_vaccinated,cumulative_at_least_one_dose,cumulative_booster_recip_count,cumulative_bivalent_booster_recip_count,booster_eligible_population,bivalent_booster_eligible_population
188,Alameda,2020-08-21,-41.0,-14.0,-7.0,-61.0,-51.0,20.0,17929.0,3.0,...,245.0,20910.0,24.0,24.0,0.0,24.0,0.0,0.0,1405462.0,1405462.0
189,Alameda,2020-08-22,-43.0,-15.0,-13.0,-52.0,-19.0,10.0,18021.0,4.0,...,105.0,21015.0,25.0,25.0,0.0,25.0,0.0,0.0,1405462.0,1405462.0
190,Alameda,2020-08-23,-43.0,-19.0,-18.0,-52.0,-21.0,9.0,18115.0,2.0,...,72.0,21087.0,25.0,25.0,0.0,25.0,0.0,0.0,1405462.0,1405462.0
191,Alameda,2020-08-24,-38.0,-18.0,-10.0,-63.0,-54.0,21.0,18338.0,9.0,...,263.0,21350.0,25.0,25.0,0.0,25.0,0.0,0.0,1405462.0,1405462.0
192,Alameda,2020-08-25,-38.0,-14.0,5.0,-62.0,-54.0,21.0,18533.0,1.0,...,293.0,21643.0,31.0,31.0,0.0,31.0,0.0,0.0,1405462.0,1405462.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3036,Merced,2022-08-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3037,Merced,2022-08-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3038,Merced,2022-08-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3039,Merced,2022-09-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3040,Merced,2022-09-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df.sort_values(by='date',ascending=True)

,County,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline,cumulative_cases,deaths,...,positive_tests,cumulative_positive_tests,cumulative_total_doses,total_partially_vaccinated,cumulative_fully_vaccinated,cumulative_at_least_one_dose,cumulative_booster_recip_count,cumulative_bivalent_booster_recip_count,booster_eligible_population,bivalent_booster_eligible_population
188,Alameda,2020-08-21,-41.0,-14.0,-7.0,-61.0,-51.0,20.0,17929.0,3.0,...,245.0,20910.0,24.0,24.0,0.0,24.0,0.0,0.0,1405462.0,1405462.0
2600,Alameda,2020-08-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2859,Merced,2020-08-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1162,Merced,2020-08-21,-22.0,-11.0,NaN,-15.0,-33.0,8.0,7770.0,2.0,...,90.0,7874.0,1.0,1.0,0.0,1.0,0.0,0.0,158662.0,158662.0
189,Alameda,2020-08-22,-43.0,-15.0,-13.0,-52.0,-19.0,10.0,18021.0,4.0,...,105.0,21015.0,25.0,25.0,0.0,25.0,0.0,0.0,1405462.0,1405462.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,Alameda,2022-09-09,-25.0,-14.0,1.0,-42.0,-36.0,9.0,344511.0,1.0,...,286.0,421618.0,3994125.0,106515.0,1394336.0,1500949.0,492544.0,7778.0,1405462.0,1405462.0
938,Alameda,2022-09-10,-26.0,-14.0,15.0,-32.0,-14.0,2.0,344692.0,0.0,...,177.0,421795.0,3995901.0,106515.0,1394472.0,1501085.0,493944.0,9161.0,1405462.0,1405462.0
1912,Merced,2022-09-10,-8.0,-6.0,72.0,-23.0,7.0,0.0,73217.0,1.0,...,19.0,85551.0,413248.0,20349.0,157746.0,178106.0,55370.0,593.0,158662.0,158662.0
2781,Alameda,2022-09-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3040,Merced,2022-09-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
result = df.dropna(axis=0, thresh=22)

In [24]:
#export as 'result.csv'
result.to_csv('result.csv')
result

,County,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline,cumulative_cases,deaths,...,positive_tests,cumulative_positive_tests,cumulative_total_doses,total_partially_vaccinated,cumulative_fully_vaccinated,cumulative_at_least_one_dose,cumulative_booster_recip_count,cumulative_bivalent_booster_recip_count,booster_eligible_population,bivalent_booster_eligible_population
188,Alameda,2020-08-21,-41.0,-14.0,-7.0,-61.0,-51.0,20.0,17929.0,3.0,...,245.0,20910.0,24.0,24.0,0.0,24.0,0.0,0.0,1405462.0,1405462.0
189,Alameda,2020-08-22,-43.0,-15.0,-13.0,-52.0,-19.0,10.0,18021.0,4.0,...,105.0,21015.0,25.0,25.0,0.0,25.0,0.0,0.0,1405462.0,1405462.0
190,Alameda,2020-08-23,-43.0,-19.0,-18.0,-52.0,-21.0,9.0,18115.0,2.0,...,72.0,21087.0,25.0,25.0,0.0,25.0,0.0,0.0,1405462.0,1405462.0
191,Alameda,2020-08-24,-38.0,-18.0,-10.0,-63.0,-54.0,21.0,18338.0,9.0,...,263.0,21350.0,25.0,25.0,0.0,25.0,0.0,0.0,1405462.0,1405462.0
192,Alameda,2020-08-25,-38.0,-14.0,5.0,-62.0,-54.0,21.0,18533.0,1.0,...,293.0,21643.0,31.0,31.0,0.0,31.0,0.0,0.0,1405462.0,1405462.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1908,Merced,2022-09-06,-5.0,-8.0,10.0,-28.0,-10.0,2.0,73092.0,0.0,...,98.0,85410.0,412611.0,20356.0,157700.0,178067.0,54879.0,107.0,158662.0,158662.0
1909,Merced,2022-09-07,-6.0,-4.0,13.0,-25.0,-8.0,2.0,73132.0,0.0,...,50.0,85460.0,412750.0,20350.0,157718.0,178079.0,54972.0,199.0,158662.0,158662.0
1910,Merced,2022-09-08,-6.0,-9.0,14.0,-24.0,-4.0,2.0,73167.0,1.0,...,36.0,85496.0,412912.0,20348.0,157729.0,178088.0,55093.0,318.0,158662.0,158662.0
1911,Merced,2022-09-09,-10.0,-7.0,27.0,-28.0,-5.0,1.0,73196.0,0.0,...,36.0,85532.0,413114.0,20343.0,157741.0,178095.0,55259.0,483.0,158662.0,158662.0
1912,Merced,2022-09-10,-8.0,-6.0,72.0,-23.0,7.0,0.0,73217.0,1.0,...,19.0,85551.0,413248.0,20349.0,157746.0,178106.0,55370.0,593.0,158662.0,158662.0